### ISSUE TITLE
SVG attributes are broken

### ISSUE THREAD

**Issue by koenkivits** [ForsakenHarmony/preact-feather#1]
Hi! :wave: First off: thanks for this library!

I noticed that icon rendering was a off for me, and it was especially noticable on the info icon, which looks like this for me right now:

![screenshot from 2018-03-14 20-03-11](https://user-images.githubusercontent.com/1873829/37425192-d0bd4508-27c2-11e8-9bf9-bb6f95f2d775.png)

Turns out that the library treats all SVG attributes as camelCase. This is fine for React because it [translates](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes) those attributes to kebab-case, but Preact doesn't do this.

I _could_ work around it by using `preact-compat`, but in that case I might as well also use `react-feather` instead, and I really want to try to keep it Preact-only and avoid any unnecessary dependencies.

I'm willing to open a PR to update all the attributes if you want. :slightly_smiling_face:

**Comment by ForsakenHarmony** [comment]
sure I'd be open for a PR, you'll want to check out submodules and modify the build script in `bin/build.js` though

**Comment by koenkivits** [comment]
Thanks for the pointers! I'll have a look tomorrow
