### ISSUE TITLE
JS File size gets too big.

### ISSUE THREAD

**Issue by IrvingArmenta** [ForsakenHarmony/preact-feather#3]
Hello, I'm Trying to maintain a small Javascript file, but this package increase the size about 100kb. or more 
I'm not sure if that is a bug, or is the intended size, are all the svg objects elements included? even when just using one like the example: 
```
import { Camera } from "preact-feather" 
```
Thank you.

**Comment by ForsakenHarmony** [comment]
I don't know what exactly causes it, but for some reason treeshaking is broken

**Comment by ForsakenHarmony** [comment]
Fixed in 3.0.0
