### ISSUE TITLE
Individual icon files not included?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [ForsakenHarmony/preact-feather#5]
The README suggests that importing "preact-feather/dist/icons/camera" would work, but it seems that only type definitions are in that folder

**Comment by ForsakenHarmony** [comment]
Oh, weird I might have broken that at some point

If you have a treeshaking bundler it should be fine to just import from `preact-feather` but I'll look into it

**Comment by ForsakenHarmony** [comment]
Yeah was most likely the microbundle transition, do you have a use case that requires it?

**Comment by vpzomtrrfrt** [comment]
Not required so much as I'm personally uncomfortable with depending on tree-shaking to do the right thing

**Comment by ForsakenHarmony** [comment]
Published `v4.1.0` with the individual icons
